all:
	@echo "YAH DIDNT READ THE FILE DID YAH?"
dev:
	@echo "===== Removing Files at Deploment Location /var/www/html ====="
	sudo rm -rf /var/www/html/*
	@echo "===== Copying Files From Src public_html to  Deploment Location /var/www/html ====="
	sudo cp -rpv public_html/* /var/www/html/
clean:
	@echo "===== Copying Files From Src public_html to  Deploment Location /var/www/html ====="
	sudo rm -rf /var/www/html/*
prod:
	@echo "===== Copying Files From Src public_html to  Deploment Location /var/www/html ====="
